'use client';
import { Canvas, ThreeEvent, useFrame, useThree } from '@react-three/fiber';
import { ContactShadows, Environment, Html, OrbitControls, RoundedBox } from '@react-three/drei';
import * as THREE from 'three'; import { useEffect, useMemo, useRef, useState } from 'react';
import { useSimulator } from '@/lib/store'; import { calculate } from '@/lib/biomechanics'; import { Pose, TargetKey, Vec3 } from '@/lib/types';
import { AnatomicalForm, FormKind, makeSegmentTransform } from './anatomy/AnatomicalGeometry';

const skin='#d6a087', bone='#ded7c9';
function Segment({a,b,r=.09,color=skin}:{a:Vec3;b:Vec3;r?:number;color?:string}){const t=makeSegmentTransform(a,b);return <mesh position={t.position} quaternion={t.quaternion} scale={[r,t.length,r]}><AnatomicalForm kind="joint"/><meshStandardMaterial color={color} roughness={.82}/></mesh>}
function solveJoint(a:Vec3,b:Vec3,l1:number,l2:number,bend:number):Vec3{const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),d=Math.min(l1+l2-.002,av.distanceTo(bv)),dir=bv.clone().sub(av).normalize();const x=(l1*l1-l2*l2+d*d)/(2*d),h=Math.sqrt(Math.max(0,l1*l1-x*x));let perp=new THREE.Vector3(0,0,bend).cross(dir).normalize();if(perp.length()<.1)perp=new THREE.Vector3(bend,0,0);return av.add(dir.multiplyScalar(x)).add(perp.multiplyScalar(h)).toArray() as Vec3}
function Muscle({position,scale,id,side='center',rotation=[0,0,0],kind}:{position:Vec3;scale:Vec3;id:string;side?:string;rotation?:Vec3;kind?:FormKind}){const mesh=useRef<THREE.Mesh>(null),display=useRef(0);const {pose,weights,selected,setSelected}=useSimulator();const raw=calculate(pose,weights.left,weights.right).activations[`${side}:${id}`]??calculate(pose,weights.left,weights.right).activations[`center:${id}`]??0;const value=raw<.1?raw*.12:Math.pow((raw-.1)/.9,.82);const shape=kind??(['pectorals','trapezius','lats','abs','obliques','erectors'].includes(id)?'sheet':['latDelts','glutes'].includes(id)?'fan':['calves'].includes(id)?'tapered':'fusiform');useFrame((_,dt)=>{const m=mesh.current?.material as THREE.MeshStandardMaterial;if(!m)return;display.current=THREE.MathUtils.damp(display.current,value,6,dt);const base=new THREE.Color('#914d43'),warm=new THREE.Color('#b5282e'),hot=new THREE.Color('#e1111b');m.color.lerpColors(base,display.current<.55?warm:hot,display.current);m.emissive.set('#650006').multiplyScalar(Math.max(0,display.current-.62)*.18);m.opacity=THREE.MathUtils.damp(m.opacity,selected&&selected!==id?.32:1,8,dt)});return <mesh ref={mesh} position={position} rotation={rotation} scale={scale} onClick={e=>{e.stopPropagation();setSelected(selected===id?null:id)}}><AnatomicalForm kind={shape}/><meshStandardMaterial transparent color="#914d43" roughness={.73}/></mesh>}
function Handle({id,position}:{id:TargetKey;position:Vec3}){const setTarget=useSimulator(s=>s.setTarget),[hover,setHover]=useState(false),drag=useRef(false);const onMove=(e:ThreeEvent<PointerEvent>)=>{if(!drag.current)return;e.stopPropagation();const p=e.point;setTarget(id,[p.x,Math.max(.06,Math.min(2.55,p.y)),Math.max(-.75,Math.min(.75,p.z))]);};return <mesh position={position} onPointerOver={()=>{setHover(true);document.body.style.cursor='grab'}} onPointerOut={()=>{setHover(false);document.body.style.cursor='default'}} onPointerDown={e=>{e.stopPropagation();drag.current=true;(e.target as Element).setPointerCapture(e.pointerId);document.body.style.cursor='grabbing'}} onPointerUp={e=>{drag.current=false;(e.target as Element).releasePointerCapture(e.pointerId);document.body.style.cursor='grab'}} onPointerMove={onMove}><sphereGeometry args={[hover?.1:.075,20,20]}/><meshStandardMaterial color={hover?'#e9b75b':'#dfd3b8'} emissive={hover?'#9a6818':'#000'} transparent opacity={hover?.95:.42}/></mesh>}
function Human(){const {pose,weights}=useSimulator();const shoulderY=pose.pelvis[1]+.69,hipY=pose.pelvis[1],chestZ=-pose.chestLean*.2;const ls:Vec3=[-.39,shoulderY,chestZ],rs:Vec3=[.39,shoulderY,chestZ],lh:Vec3=[-.23,hipY,pose.pelvis[2]],rh:Vec3=[.23,hipY,pose.pelvis[2]];const le=solveJoint(ls,pose.leftHand,.48,.47,-1),re=solveJoint(rs,pose.rightHand,.48,.47,1),lk=solveJoint(lh,pose.leftFoot,.58,.57,1),rk=solveJoint(rh,pose.rightFoot,.58,.57,1);return <group>
 <group position={[0,shoulderY+.34,chestZ]}><mesh scale={[.16,.21,.16]}><sphereGeometry args={[1,24,20]}/><meshStandardMaterial color={bone} roughness={.86}/></mesh><mesh position={[0,-.025,-.135]} scale={[.11,.12,.08]}><sphereGeometry args={[1,18,14]}/><meshStandardMaterial color={bone} roughness={.9}/></mesh></group><Segment a={[0,shoulderY+.14,chestZ]} b={[0,shoulderY+.25,chestZ]} r={.075} color={bone}/>
 <mesh position={[0,pose.pelvis[1]+.38,chestZ]} scale={[.46,.76,.25]} rotation={[0,0,Math.PI]}><AnatomicalForm kind="fan"/><meshStandardMaterial color="#b87a68" roughness={.86}/></mesh><mesh position={[0,hipY+.02,pose.pelvis[2]]} scale={[.42,.38,.28]} rotation={[0,0,Math.PI]}><AnatomicalForm kind="fan"/><meshStandardMaterial color="#a9695e" roughness={.88}/></mesh>
 {[['left',ls,le,pose.leftHand,lh,lk,pose.leftFoot],['right',rs,re,pose.rightHand,rh,rk,pose.rightFoot]].map((x:any)=>{const [side,s,e,hand,hip,knee,foot]=x;const armT=makeSegmentTransform(s,e),foreT=makeSegmentTransform(e,hand),thighT=makeSegmentTransform(hip,knee),calfT=makeSegmentTransform(knee,foot);return <group key={side}><Segment a={s} b={e} r={.1}/><Segment a={e} b={hand} r={.078}/><Segment a={hip} b={knee} r={.125}/><Segment a={knee} b={foot} r={.095}/><mesh position={hand} scale={[.095,.19,.055]} quaternion={foreT.quaternion}><AnatomicalForm kind="tapered"/><meshStandardMaterial color={bone} roughness={.9}/></mesh><RoundedBox position={[foot[0],foot[1],foot[2]-.075]} scale={[.21,.1,.36]} radius={.07} smoothness={3}><meshStandardMaterial color={bone} roughness={.9}/></RoundedBox>
 <group position={armT.position} quaternion={armT.quaternion}><Muscle id="biceps" side={side} position={[0,0,-.072]} scale={[.1,armT.length*.78,.075]}/><Muscle id="triceps" side={side} position={[0,0,.075]} scale={[.092,armT.length*.85,.08]}/></group><Muscle id="latDelts" side={side} position={s} scale={[.17,.28,.13]} kind="fan"/>
 <group position={thighT.position} quaternion={thighT.quaternion}><Muscle id="quads" side={side} position={[0,0,-.08]} scale={[.14,thighT.length*.88,.11]}/><Muscle id="hamstrings" side={side} position={[0,0,.095]} scale={[.12,thighT.length*.86,.095]}/></group><group position={calfT.position} quaternion={calfT.quaternion}><Muscle id="calves" side={side} position={[0,.03,.075]} scale={[.115,calfT.length*.78,.095]} kind="tapered"/></group><Muscle id="glutes" side={side} position={[hip[0],hip[1]+.1,hip[2]+.2]} scale={[.21,.34,.16]} kind="fan"/>
 {weights[side as 'left'|'right']>0&&<group position={hand} rotation={[0,0,Math.PI/2]}><mesh><cylinderGeometry args={[.035,.035,.34,12]}/><meshStandardMaterial color="#55534f" metalness={.65}/></mesh>{[-.16,.16].map(z=><mesh key={z} position={[0,z,0]}><cylinderGeometry args={[.12,.12,.1,16]}/><meshStandardMaterial color="#272724" metalness={.5}/></mesh>)}</group>}<Handle id={`${side}Hand` as TargetKey} position={hand}/><Handle id={`${side}Foot` as TargetKey} position={foot}/></group>})}
 <Muscle id="antDelts" side="left" position={[ls[0]+.025,ls[1],ls[2]-.09]} scale={[.11,.24,.075]} rotation={[0,0,-.3]} kind="fan"/><Muscle id="antDelts" side="right" position={[rs[0]-.025,rs[1],rs[2]-.09]} scale={[.11,.24,.075]} rotation={[0,0,.3]} kind="fan"/>
 <Muscle id="postDelts" side="left" position={[ls[0]+.025,ls[1],ls[2]+.09]} scale={[.1,.22,.07]} rotation={[0,0,-.28]} kind="fan"/><Muscle id="postDelts" side="right" position={[rs[0]-.025,rs[1],rs[2]+.09]} scale={[.1,.22,.07]} rotation={[0,0,.28]} kind="fan"/>
 <Muscle id="pectorals" side="left" position={[-.19,shoulderY-.16,chestZ-.245]} scale={[.205,.34,.055]} rotation={[0,0,-Math.PI/2]} kind="fan"/><Muscle id="pectorals" side="right" position={[.19,shoulderY-.16,chestZ-.245]} scale={[.205,.34,.055]} rotation={[0,0,Math.PI/2]} kind="fan"/>
 {[-.31,-.43,-.55].map(off=><group key={off}><Muscle id="abs" position={[-.075,shoulderY+off,chestZ-.26]} scale={[.068,.16,.045]} kind="fusiform"/><Muscle id="abs" position={[.075,shoulderY+off,chestZ-.26]} scale={[.068,.16,.045]} kind="fusiform"/></group>)}
 <Muscle id="obliques" side="left" position={[-.29,shoulderY-.45,chestZ-.19]} scale={[.105,.54,.065]} rotation={[0,0,-.12]} kind="sheet"/><Muscle id="obliques" side="right" position={[.29,shoulderY-.45,chestZ-.19]} scale={[.105,.54,.065]} rotation={[0,0,.12]} kind="sheet"/>
 <Muscle id="trapezius" position={[0,shoulderY+.01,chestZ+.24]} scale={[.37,.48,.05]} rotation={[0,0,Math.PI]} kind="fan"/><Muscle id="lats" side="left" position={[-.2,shoulderY-.31,chestZ+.245]} scale={[.18,.58,.05]} rotation={[0,0,-.08]} kind="fan"/><Muscle id="lats" side="right" position={[.2,shoulderY-.31,chestZ+.245]} scale={[.18,.58,.05]} rotation={[0,0,.08]} kind="fan"/><Muscle id="erectors" position={[0,shoulderY-.47,chestZ+.255]} scale={[.105,.72,.045]} kind="fusiform"/>
 </group>}
function CameraRig(){const view=useSimulator(s=>s.cameraView),{camera}=useThree();useEffect(()=>{const pos=view==='front'?[0,1.25,4.2]:view==='back'?[0,1.25,-4.2]:view==='left'?[-4.2,1.25,0]:view==='right'||view==='side'?[4.2,1.25,0]:[3.1,2.2,3.4];camera.position.set(...pos as [number,number,number]);camera.lookAt(0,1.2,0)},[view,camera]);return null}
export default function AnatomyViewer(){return <Canvas shadows camera={{position:[3.1,2.2,3.4],fov:35}} gl={{antialias:true}}><color attach="background" args={['#111412']}/><fog attach="fog" args={['#111412',5,9]}/><ambientLight intensity={.75}/><directionalLight position={[3,5,4]} intensity={2.1} castShadow/><Environment preset="warehouse"/><Human/><mesh rotation={[-Math.PI/2,0,0]} position={[0,0,0]} receiveShadow><circleGeometry args={[3.3,64]}/><meshStandardMaterial color="#1a1e1b" roughness={1}/></mesh><ContactShadows position={[0,.01,0]} opacity={.65} blur={2.5} scale={5}/><OrbitControls makeDefault target={[0,1.15,0]} enableDamping dampingFactor={.08} minDistance={2.4} maxDistance={7}/><CameraRig/></Canvas>}
