'use client';
import { Canvas, ThreeEvent, useFrame, useThree } from '@react-three/fiber';
import { ContactShadows, Environment, Html, OrbitControls, RoundedBox } from '@react-three/drei';
import * as THREE from 'three'; import { useEffect, useMemo, useRef, useState } from 'react';
import { useSimulator } from '@/lib/store'; import { calculate } from '@/lib/biomechanics'; import { Pose, TargetKey, Vec3 } from '@/lib/types';

const skin='#d6a087', bone='#ded7c9';
function Segment({a,b,r=.09,color=skin}:{a:Vec3;b:Vec3;r?:number;color?:string}){const mid=useMemo(()=>new THREE.Vector3(),[]),q=useMemo(()=>new THREE.Quaternion(),[]);const len=Math.hypot(b[0]-a[0],b[1]-a[1],b[2]-a[2]);mid.set((a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2);q.setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(b[0]-a[0],b[1]-a[1],b[2]-a[2]).normalize());return <mesh position={mid} quaternion={q}><capsuleGeometry args={[r,Math.max(.01,len-r*2),8,16]}/><meshStandardMaterial color={color} roughness={.72}/></mesh>}
function solveJoint(a:Vec3,b:Vec3,l1:number,l2:number,bend:number):Vec3{const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),d=Math.min(l1+l2-.002,av.distanceTo(bv)),dir=bv.clone().sub(av).normalize();const x=(l1*l1-l2*l2+d*d)/(2*d),h=Math.sqrt(Math.max(0,l1*l1-x*x));let perp=new THREE.Vector3(0,0,bend).cross(dir).normalize();if(perp.length()<.1)perp=new THREE.Vector3(bend,0,0);return av.add(dir.multiplyScalar(x)).add(perp.multiplyScalar(h)).toArray() as Vec3}
function Muscle({position,scale,id,side='center',rotation=[0,0,0]}:{position:Vec3;scale:Vec3;id:string;side?:string;rotation?:Vec3}){const mesh=useRef<THREE.Mesh>(null);const {pose,weights,selected,setSelected}=useSimulator();const value=calculate(pose,weights.left,weights.right).activations[`${side}:${id}`]??calculate(pose,weights.left,weights.right).activations[`center:${id}`]??0;useFrame(()=>{const m=mesh.current?.material as THREE.MeshStandardMaterial;if(!m)return;const base=new THREE.Color('#b36f63'),hot=new THREE.Color('#ff2929');m.color.lerpColors(base,hot,value);m.emissive.set('#9c0712').multiplyScalar(value*.22);m.opacity=THREE.MathUtils.damp(m.opacity,selected&&selected!==id?.25:1,8,1/60)});return <mesh ref={mesh} position={position} rotation={rotation} scale={scale} onClick={e=>{e.stopPropagation();setSelected(selected===id?null:id)}}><sphereGeometry args={[1,18,14]}/><meshStandardMaterial transparent color="#b36f63" roughness={.58}/></mesh>}
function Handle({id,position}:{id:TargetKey;position:Vec3}){const setTarget=useSimulator(s=>s.setTarget),[hover,setHover]=useState(false),drag=useRef(false);const onMove=(e:ThreeEvent<PointerEvent>)=>{if(!drag.current)return;e.stopPropagation();const p=e.point;setTarget(id,[p.x,Math.max(.06,Math.min(2.55,p.y)),Math.max(-.75,Math.min(.75,p.z))]);};return <mesh position={position} onPointerOver={()=>{setHover(true);document.body.style.cursor='grab'}} onPointerOut={()=>{setHover(false);document.body.style.cursor='default'}} onPointerDown={e=>{e.stopPropagation();drag.current=true;(e.target as Element).setPointerCapture(e.pointerId);document.body.style.cursor='grabbing'}} onPointerUp={e=>{drag.current=false;(e.target as Element).releasePointerCapture(e.pointerId);document.body.style.cursor='grab'}} onPointerMove={onMove}><sphereGeometry args={[hover?.1:.075,20,20]}/><meshStandardMaterial color={hover?'#e9b75b':'#dfd3b8'} emissive={hover?'#9a6818':'#000'} transparent opacity={hover?.95:.42}/></mesh>}
function Human(){const {pose,weights}=useSimulator();const shoulderY=pose.pelvis[1]+.69,hipY=pose.pelvis[1],chestZ=-pose.chestLean*.2;const ls:Vec3=[-.39,shoulderY,chestZ],rs:Vec3=[.39,shoulderY,chestZ],lh:Vec3=[-.23,hipY,pose.pelvis[2]],rh:Vec3=[.23,hipY,pose.pelvis[2]];const le=solveJoint(ls,pose.leftHand,.48,.47,-1),re=solveJoint(rs,pose.rightHand,.48,.47,1),lk=solveJoint(lh,pose.leftFoot,.58,.57,1),rk=solveJoint(rh,pose.rightFoot,.58,.57,1);return <group>
 <mesh position={[0,shoulderY+.34,chestZ]}><sphereGeometry args={[.18,24,20]}/><meshStandardMaterial color={skin}/></mesh><Segment a={[0,shoulderY+.17,chestZ]} b={[0,shoulderY+.25,chestZ]} r={.09}/>
 <mesh position={[0,pose.pelvis[1]+.37,chestZ]} scale={[.48,.64,.26]}><sphereGeometry args={[1,24,18]}/><meshStandardMaterial color={skin} roughness={.8}/></mesh><mesh position={[0,hipY,pose.pelvis[2]]} scale={[.38,.24,.27]}><sphereGeometry args={[1,20,14]}/><meshStandardMaterial color={skin}/></mesh>
 {[['left',ls,le,pose.leftHand,lh,lk,pose.leftFoot],['right',rs,re,pose.rightHand,rh,rk,pose.rightFoot]].map((x:any)=>{const [side,s,e,hand,hip,knee,foot]=x;return <group key={side}><Segment a={s} b={e} r={.105}/><Segment a={e} b={hand} r={.085}/><Segment a={hip} b={knee} r={.13}/><Segment a={knee} b={foot} r={.105}/><mesh position={hand}><sphereGeometry args={[.105,16,12]}/><meshStandardMaterial color={skin}/></mesh><mesh position={foot} scale={[.13,.08,.24]}><sphereGeometry args={[1,16,12]}/><meshStandardMaterial color={skin}/></mesh>
 <Muscle id="latDelts" side={side} position={s} scale={[.16,.13,.13]}/><Muscle id="biceps" side={side} position={[(s[0]+e[0])/2,(s[1]+e[1])/2,(s[2]+e[2])/2]} scale={[.115,.24,.105]}/><Muscle id="triceps" side={side} position={[(s[0]+e[0])/2,(s[1]+e[1])/2,(s[2]+e[2])/2+.07]} scale={[.09,.23,.1]}/>
 <Muscle id="quads" side={side} position={[(hip[0]+knee[0])/2,(hip[1]+knee[1])/2,(hip[2]+knee[2])/2-.08]} scale={[.145,.3,.13]}/><Muscle id="hamstrings" side={side} position={[(hip[0]+knee[0])/2,(hip[1]+knee[1])/2,(hip[2]+knee[2])/2+.1]} scale={[.12,.28,.1]}/><Muscle id="calves" side={side} position={[(knee[0]+foot[0])/2,(knee[1]+foot[1])/2,(knee[2]+foot[2])/2+.08]} scale={[.115,.25,.11]}/><Muscle id="glutes" side={side} position={[hip[0],hip[1]+.1,hip[2]+.2]} scale={[.2,.2,.15]}/>
 {weights[side as 'left'|'right']>0&&<group position={hand} rotation={[0,0,Math.PI/2]}><mesh><cylinderGeometry args={[.035,.035,.34,12]}/><meshStandardMaterial color="#55534f" metalness={.65}/></mesh>{[-.16,.16].map(z=><mesh key={z} position={[0,z,0]}><cylinderGeometry args={[.12,.12,.1,16]}/><meshStandardMaterial color="#272724" metalness={.5}/></mesh>)}</group>}<Handle id={`${side}Hand` as TargetKey} position={hand}/><Handle id={`${side}Foot` as TargetKey} position={foot}/></group>})}
 <Muscle id="pectorals" side="left" position={[-.19,shoulderY-.16,chestZ-.23]} scale={[.2,.17,.06]}/><Muscle id="pectorals" side="right" position={[.19,shoulderY-.16,chestZ-.23]} scale={[.2,.17,.06]}/><Muscle id="abs" position={[0,shoulderY-.46,chestZ-.255]} scale={[.16,.31,.055]}/><Muscle id="obliques" side="left" position={[-.27,shoulderY-.44,chestZ-.18]} scale={[.1,.28,.07]} rotation={[0,0,-.12]}/><Muscle id="obliques" side="right" position={[.27,shoulderY-.44,chestZ-.18]} scale={[.1,.28,.07]} rotation={[0,0,.12]}/><Muscle id="trapezius" position={[0,shoulderY+.04,chestZ+.23]} scale={[.35,.25,.055]}/><Muscle id="lats" side="left" position={[-.2,shoulderY-.32,chestZ+.24]} scale={[.16,.33,.055]}/><Muscle id="lats" side="right" position={[.2,shoulderY-.32,chestZ+.24]} scale={[.16,.33,.055]}/><Muscle id="erectors" position={[0,shoulderY-.48,chestZ+.25]} scale={[.11,.39,.05]}/>
 </group>}
function CameraRig(){const view=useSimulator(s=>s.cameraView),{camera}=useThree();useEffect(()=>{const pos=view==='front'?[0,1.25,4.2]:view==='back'?[0,1.25,-4.2]:view==='left'?[-4.2,1.25,0]:view==='right'||view==='side'?[4.2,1.25,0]:[3.1,2.2,3.4];camera.position.set(...pos as [number,number,number]);camera.lookAt(0,1.2,0)},[view,camera]);return null}
export default function AnatomyViewer(){return <Canvas shadows camera={{position:[3.1,2.2,3.4],fov:35}} gl={{antialias:true}}><color attach="background" args={['#111412']}/><fog attach="fog" args={['#111412',5,9]}/><ambientLight intensity={.75}/><directionalLight position={[3,5,4]} intensity={2.1} castShadow/><Environment preset="warehouse"/><Human/><mesh rotation={[-Math.PI/2,0,0]} position={[0,0,0]} receiveShadow><circleGeometry args={[3.3,64]}/><meshStandardMaterial color="#1a1e1b" roughness={1}/></mesh><ContactShadows position={[0,.01,0]} opacity={.65} blur={2.5} scale={5}/><OrbitControls makeDefault target={[0,1.15,0]} enableDamping dampingFactor={.08} minDistance={2.4} maxDistance={7}/><CameraRig/></Canvas>}
