'use client';
import dynamic from 'next/dynamic'; import { useEffect, useMemo } from 'react'; import { useSimulator } from '@/lib/store'; import { presets } from '@/lib/presets'; import { calculate } from '@/lib/biomechanics'; import { muscleDefinitions } from '@/lib/muscles'; import { Pose } from '@/lib/types';
const Viewer=dynamic(()=>import('./AnatomyViewer'),{ssr:false,loading:()=> <div className="loading"><span/><p>Preparing anatomy lab…</p></div>});
const mix=(a:number,b:number,t:number)=>a+(b-a)*(t*t*(3-2*t));const interpolate=(a:Pose,b:Pose,t:number):Pose=>({leftHand:a.leftHand.map((v,i)=>mix(v,b.leftHand[i],t)) as any,rightHand:a.rightHand.map((v,i)=>mix(v,b.rightHand[i],t)) as any,leftFoot:a.leftFoot.map((v,i)=>mix(v,b.leftFoot[i],t)) as any,rightFoot:a.rightFoot.map((v,i)=>mix(v,b.rightFoot[i],t)) as any,pelvis:a.pelvis.map((v,i)=>mix(v,b.pelvis[i],t)) as any,chestLean:mix(a.chestLean,b.chestLean,t)});
export default function Simulator(){const s=useSimulator();useEffect(()=>{if(!s.playing)return;let id=0,last=performance.now();const tick=(now:number)=>{const dt=(now-last)/1000;last=now;let p=s.progress+dt*.42*s.speed;if(p>=1){if(s.loop)p=0;else{s.setPlaying(false);p=1}}s.setProgress(p);s.setPose(interpolate(s.start,s.end,p));id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[s.playing,s.loop,s.speed,s.start,s.end]);const bio=useMemo(()=>calculate(s.pose,s.weights.left,s.weights.right),[s.pose,s.weights]);const rows=muscleDefinitions.flatMap(m=>['center','left','right'].map(side=>({id:m.id,name:`${side==='center'?'':side+' '}${m.name}`,v:bio.activations[`${side}:${m.id}`]??-1}))).filter(x=>x.v>=0).sort((a,b)=>b.v-a.v).slice(0,10);return <main>
 <header><div className="brand"><i/>KINETIC <b>ATLAS</b></div><div className="status"><span/> LIVE SIMULATION</div><div className="views">{['front','back','left','right'].map(v=><button key={v} onClick={()=>s.setCameraView(v)}>{v}</button>)}</div></header>
 <section className="workspace"><aside className="panel left"><label className="eyebrow">EXERCISE LIBRARY</label><h2>Movement</h2><div className="presets">{presets.map(p=><button className={s.preset===p.id?'active':''} key={p.id} onClick={()=>s.loadPreset(p.id)}><span>{p.name}</span><em>›</em></button>)}</div><hr/><label className="eyebrow">EXTERNAL LOAD</label>{(['left','right'] as const).map(side=><div className="weight" key={side}><div><span>{side} dumbbell</span><b>{s.weights[side]} lb</b></div><input aria-label={`${side} dumbbell weight`} type="range" min="0" max="100" step="5" value={s.weights[side]} onChange={e=>s.setWeight(side,+e.target.value)}/></div>)}<hr/><label className="eyebrow">POSE CAPTURE</label><div className="capture"><button onClick={()=>s.capture('start')}>Set start</button><button onClick={()=>s.capture('end')}>Set end</button></div><button className="reset" onClick={s.reset}>↺ Reset all</button></aside>
 <div className="stage"><Viewer/><div className="hint">Drag the illuminated hands or feet · Orbit to inspect</div><div className="mode">MUSCLE VIEW</div></div>
 <aside className="panel right"><label className="eyebrow">REAL-TIME ANALYSIS</label><h2>Muscle activity</h2><div className="activity">{rows.map((r,i)=><button key={r.name} className={s.selected===r.id?'chosen':''} onClick={()=>s.setSelected(s.selected===r.id?null:r.id)}><div><span>{r.name}</span><b>{Math.round(r.v*100)}%</b></div><i><em style={{width:`${r.v*100}%`}}/></i></button>)}</div>{s.selected&&<div className="muscle-info"><button onClick={()=>s.setSelected(null)}>×</button><label>SELECTED MUSCLE</label><h3>{muscleDefinitions.find(x=>x.id===s.selected)?.name}</h3><p>{muscleDefinitions.find(x=>x.id===s.selected)?.function}</p><small>Role changes continuously with pose and load.</small></div>}<details><summary>Biomechanics <span>⌄</span></summary>{Object.entries(bio.torques).map(([k,v])=><div className="metric" key={k}><span>{k} torque</span><b>{v.toFixed(1)} Nm</b></div>)}</details></aside></section>
 <footer><div className="transport"><button className="play" onClick={()=>s.setPlaying(!s.playing)}>{s.playing?'Ⅱ':'▶'}</button><button onClick={()=>{s.setProgress(0);s.setPose(s.start);s.setPlaying(true)}}>↺</button></div><div className="timeline"><div><span>START</span><b>{Math.round(s.progress*100)}%</b><span>END</span></div><input aria-label="Movement timeline" type="range" min="0" max="1" step=".001" value={s.progress} onChange={e=>{const p=+e.target.value;s.setPlaying(false);s.setProgress(p);s.setPose(interpolate(s.start,s.end,p))}}/></div><label className="toggle"><input type="checkbox" checked={s.loop} onChange={e=>s.setLoop(e.target.checked)}/><i/> LOOP</label><select aria-label="Playback speed" value={s.speed} onChange={e=>s.setSpeed(+e.target.value)}><option value=".5">0.5×</option><option value="1">1×</option><option value="1.5">1.5×</option></select><p className="disclaimer">Educational estimate · Not medical advice</p></footer>
 </main>}
