'use client';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { useMemo, useRef } from 'react';
import { useSimulator } from '@/lib/store';
import { calculate } from '@/lib/biomechanics';
import { neutralPose } from '@/lib/presets';
import { Pose, Vec3 } from '@/lib/types';

type Segment='torso'|'pelvis'|'leftUpperArm'|'leftForearm'|'leftHand'|'rightUpperArm'|'rightForearm'|'rightHand'|'leftThigh'|'leftShin'|'leftFoot'|'rightThigh'|'rightShin'|'rightFoot';
const segments:Segment[]=['torso','pelvis','leftUpperArm','leftForearm','leftHand','rightUpperArm','rightForearm','rightHand','leftThigh','leftShin','leftFoot','rightThigh','rightShin','rightFoot'];
const baseColor=new THREE.Color('#8f4038'),warm=new THREE.Color('#bd292f'),hot=new THREE.Color('#e20f1a');

function solveJoint(a:Vec3,b:Vec3,l1:number,l2:number,bend:number):Vec3{const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),d=Math.min(l1+l2-.002,av.distanceTo(bv)),dir=bv.clone().sub(av).normalize();const x=(l1*l1-l2*l2+d*d)/(2*d),h=Math.sqrt(Math.max(0,l1*l1-x*x));let perp=new THREE.Vector3(0,0,bend).cross(dir).normalize();if(perp.length()<.1)perp=new THREE.Vector3(bend,0,0);return av.add(dir.multiplyScalar(x)).add(perp.multiplyScalar(h)).toArray() as Vec3}
function joints(p:Pose){const sy=p.pelvis[1]+.58,z=-p.chestLean*.2,ls:Vec3=[-.23,sy,z],rs:Vec3=[.23,sy,z],lh:Vec3=[-.14,p.pelvis[1],p.pelvis[2]],rh:Vec3=[.14,p.pelvis[1],p.pelvis[2]];return{ls,rs,lh,rh,le:solveJoint(ls,p.leftHand,.39,.37,-1),re:solveJoint(rs,p.rightHand,.39,.37,1),lk:solveJoint(lh,p.leftFoot,.56,.54,1),rk:solveJoint(rh,p.rightFoot,.56,.54,1)}}
function frame(a:Vec3,b:Vec3){const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,-1,0),bv.clone().sub(av).normalize());return new THREE.Matrix4().compose(av,q,new THREE.Vector3(1,1,1))}
function delta(a:Vec3,b:Vec3,na:Vec3,nb:Vec3){return frame(a,b).multiply(frame(na,nb).invert())}
function muscleId(name:string){const n=name.toLowerCase();if(n.includes('biceps brach'))return'biceps';if(n.includes('triceps'))return'triceps';if(n.includes('deltoid'))return n.includes('clavicular')?'antDelts':n.includes('spinal')?'postDelts':'latDelts';if(n.includes('pectoralis'))return'pectorals';if(n.includes('trapezius'))return'trapezius';if(n.includes('latissimus'))return'lats';if(n.includes('rectus abdom'))return'abs';if(n.includes('oblique'))return'obliques';if(/erector|spinalis|longissimus|iliocostalis/.test(n))return'erectors';if(n.includes('glute'))return'glutes';if(/rectus femoris|vastus/.test(n))return'quads';if(/biceps femoris|semitendinosus|semimembranosus/.test(n))return'hamstrings';if(/gastrocnemius|soleus/.test(n))return'calves';return null}
function segmentFor(name:string,center:THREE.Vector3):Segment{const n=name.toLowerCase(),side=n.includes('left')?'left':n.includes('right')?'right':center.x<0?'left':'right';if(/hand|pollic|carp|finger|digiti|palmar/.test(n))return`${side}Hand` as Segment;if(/foot|plantar|toe|halluc/.test(n))return`${side}Foot` as Segment;if(/forearm|antebrach|pronator|supinator|flexor|extensor/.test(n)&&center.y>1.1)return`${side}Forearm` as Segment;if(/biceps brach|triceps|brachialis|deltoid|coracobrach/.test(n))return`${side}UpperArm` as Segment;if(/gastrocnemius|soleus|tibialis|fibularis|peroneus/.test(n))return`${side}Shin` as Segment;if(/femor|vastus|semitend|semimembran|adductor|gracilis|sartorius/.test(n))return`${side}Thigh` as Segment;if(/glute|piriform|obturator|gemellus/.test(n))return'pelvis';return center.y<.95?(center.x<0?'leftThigh':'rightThigh'):'torso'}

export default function RealAnatomyModel(){const gltf=useGLTF('/models/bodyparts3d-anatomy.glb');const groups=useRef<Record<Segment,THREE.Group>>({} as any);const display=useRef<Record<string,number>>({});const {pose,weights,selected,setSelected}=useSimulator();const model=useMemo(()=>{gltf.scene.updateMatrixWorld(true);const root=new THREE.Group(),box=new THREE.Box3().setFromObject(gltf.scene),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),scale=2.38/size.z;const gs={} as Record<Segment,THREE.Group>;segments.forEach(s=>{gs[s]=new THREE.Group();root.add(gs[s])});gltf.scene.traverse(o=>{if(!(o as THREE.Mesh).isMesh)return;const src=o as THREE.Mesh,g=src.geometry.clone();g.applyMatrix4(src.matrixWorld);const p=g.getAttribute('position') as THREE.BufferAttribute;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i);p.setXYZ(i,(x-center.x)*scale,(z-center.z)*scale+1.19,-(y-center.y)*scale)}g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();const c=g.boundingBox!.getCenter(new THREE.Vector3()),id=muscleId(src.name),side=src.name.toLowerCase().includes('left')?'left':src.name.toLowerCase().includes('right')?'right':'center';const mat=new THREE.MeshStandardMaterial({color:baseColor,roughness:.68,metalness:0,side:THREE.DoubleSide,transparent:true});const mesh=new THREE.Mesh(g,mat);mesh.name=src.name;mesh.userData={muscleId:id,side};mesh.castShadow=true;mesh.receiveShadow=true;mesh.onBeforeRender=()=>{};gs[segmentFor(src.name,c)].add(mesh)});groups.current=gs;if(process.env.NODE_ENV==='development'){const debug={counts:Object.fromEntries(segments.map(s=>[s,gs[s].children.length])),bounds:new THREE.Box3().setFromObject(root).getSize(new THREE.Vector3()).toArray()};(window as any).__ANATOMY_DEBUG=debug;console.info('Anatomy loaded',JSON.stringify(debug))}return root},[gltf]);
 useFrame((_,dt)=>{const j=joints(pose),n=joints(neutralPose),g=groups.current;if(!g.torso)return;const transforms:Partial<Record<Segment,THREE.Matrix4>>={torso:new THREE.Matrix4().makeTranslation(pose.pelvis[0],pose.pelvis[1]-neutralPose.pelvis[1],pose.pelvis[2]),pelvis:new THREE.Matrix4().makeTranslation(pose.pelvis[0],pose.pelvis[1]-neutralPose.pelvis[1],pose.pelvis[2]),leftUpperArm:delta(j.ls,j.le,n.ls,n.le),leftForearm:delta(j.le,pose.leftHand,n.le,neutralPose.leftHand),rightUpperArm:delta(j.rs,j.re,n.rs,n.re),rightForearm:delta(j.re,pose.rightHand,n.re,neutralPose.rightHand),leftThigh:delta(j.lh,j.lk,n.lh,n.lk),leftShin:delta(j.lk,pose.leftFoot,n.lk,neutralPose.leftFoot),rightThigh:delta(j.rh,j.rk,n.rh,n.rk),rightShin:delta(j.rk,pose.rightFoot,n.rk,neutralPose.rightFoot)};transforms.leftHand=transforms.leftForearm;transforms.rightHand=transforms.rightForearm;transforms.leftFoot=transforms.leftShin;transforms.rightFoot=transforms.rightShin;segments.forEach(s=>{const m=transforms[s];if(m){m.decompose(g[s].position,g[s].quaternion,g[s].scale)}});const acts=calculate(pose,weights.left,weights.right).activations;model.traverse(o=>{if(!(o as THREE.Mesh).isMesh)return;const m=o as THREE.Mesh,id=m.userData.muscleId as string|null,side=m.userData.side as string,target=id?(acts[`${side}:${id}`]??acts[`center:${id}`]??0):0,key=m.uuid;display.current[key]=THREE.MathUtils.damp(display.current[key]??0,target<.1?target*.1:Math.pow((target-.1)/.9,.82),6,dt);const v=display.current[key],mat=m.material as THREE.MeshStandardMaterial;mat.color.lerpColors(baseColor,v<.55?warm:hot,v);mat.emissive.set('#5f0005').multiplyScalar(Math.max(0,v-.6)*.16);mat.opacity=selected&&id!==selected?.22:1})});
 return <primitive object={model} onClick={(e:any)=>{e.stopPropagation();const id=e.object?.userData?.muscleId;if(id)setSelected(selected===id?null:id)}}/>}
useGLTF.preload('/models/bodyparts3d-anatomy.glb');
